/**
 * neon-ribbons/params.ts — Typed parameter schema for the neon ribbons generator.
 *
 * Pure data: the inspector builds its UI from this array, the randomiser
 * samples it, and `generate.ts` reads it. No React, no DOM.
 */

import type { ParamDef } from '../../schema'

/** Curve selector options shown in the inspector. */
export const CURVE_OPTIONS: { value: string; label: string }[] = [
  { value: 'swirl', label: 'Swirl / spiral' },
  { value: 'ellipse', label: 'Tilted ellipse rings' },
  { value: 'sCurve', label: 'S-curve' },
  { value: 'bezier', label: 'Bezier sweep' },
  { value: 'fan', label: 'Fan / converging lines' },
  { value: 'chevron', label: 'Arrow / chevron streaks' },
  { value: 'vortex', label: 'Vortex ring' },
]

/** Parameter schema; the inspector is auto-built from this. */
export const RIBBON_PARAMS: ParamDef[] = [
  // one ribbon is a legitimate result — exempt from MIN_EMIT
  {
    key: 'count',
    label: 'Ribbons',
    type: 'int',
    min: 1,
    max: 24,
    step: 1,
    default: 3,
    section: 'shape',
    hint: 'How many bundles to emit.',
    rand: { min: 1, max: 8 },
  },
  {
    key: 'curve',
    label: 'Curve type',
    type: 'enum',
    options: CURVE_OPTIONS,
    default: 'swirl',
    section: 'shape',
  },
  {
    key: 'strands',
    label: 'Strands per ribbon',
    type: 'int',
    min: 10,
    max: 80,
    step: 1,
    default: 28,
    section: 'shape',
    hint: 'Thin strokes per bundle — they twist, fan out and cross.',
    rand: { min: 12, max: 48 },
  },
  {
    key: 'length',
    label: 'Length',
    type: 'float',
    min: 0.2,
    max: 1.6,
    step: 0.01,
    default: 0.8,
    section: 'shape',
    unit: '×',
    hint: 'As a fraction of the canvas diagonal.',
    rand: { min: 0.4, max: 1.2 },
  },
  {
    key: 'spread',
    label: 'Spread',
    type: 'float',
    min: 0,
    max: 90,
    step: 1,
    default: 22,
    section: 'shape',
    unit: 'px',
    hint: 'Lateral fan-out of the strands.',
    rand: { min: 6, max: 44 },
  },
  {
    key: 'twist',
    label: 'Twist',
    type: 'float',
    min: 0,
    max: 2,
    step: 0.01,
    default: 0.8,
    section: 'shape',
    hint: 'How much strands weave across each other.',
    rand: { min: 0.2, max: 1.6 },
  },
  {
    key: 'taper',
    label: 'Taper',
    type: 'float',
    min: 0,
    max: 1.6,
    step: 0.01,
    default: 0.9,
    section: 'style',
    hint: 'How fast each strand thins toward its ends.',
  },
  {
    key: 'width',
    label: 'Strand width',
    type: 'float',
    min: 0.5,
    max: 24,
    step: 0.5,
    default: 5,
    section: 'style',
    unit: 'px',
    rand: { min: 1.5, max: 10 },
  },
  {
    key: 'glowRadius',
    label: 'Glow radius',
    type: 'float',
    min: 1,
    max: 48,
    step: 0.5,
    default: 14,
    section: 'style',
    unit: 'px',
    hint: 'Width of the soft coloured halo under each core.',
  },
  {
    key: 'core',
    label: 'Core brightness',
    type: 'float',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.7,
    section: 'style',
    hint: 'White-hot centre line over the coloured glow.',
  },
  {
    key: 'alpha',
    label: 'Opacity',
    type: 'float',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.8,
    section: 'style',
    rand: { min: 0.4, max: 1 },
  },
  {
    key: 'rotation',
    label: 'Rotation',
    type: 'float',
    min: 0,
    max: 360,
    step: 1,
    default: 0,
    section: 'shape',
    unit: '°',
  },
  {
    key: 'perspective',
    label: 'Perspective squash',
    type: 'float',
    min: 0.15,
    max: 1,
    step: 0.01,
    default: 0.45,
    section: 'shape',
    hint: 'Vertical squash for ellipse rings — the 3D tilt look.',
  },
  {
    key: 'colorFlow',
    label: 'Colour flow',
    type: 'float',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.7,
    section: 'style',
    hint: 'How far the palette ramp travels along each strand.',
  },
  {
    key: 'sparkle',
    label: 'Sparkles',
    type: 'float',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.5,
    section: 'style',
    hint: 'Glitter dots scattered along the paths.',
  },
]

/** Designed defaults; presets spread over these. */
export function ribbonDefaults(): Record<string, number | string> {
  return {
    count: 3,
    curve: 'swirl',
    strands: 28,
    length: 0.8,
    spread: 22,
    twist: 0.8,
    taper: 0.9,
    width: 5,
    glowRadius: 14,
    core: 0.7,
    alpha: 0.8,
    rotation: 0,
    perspective: 0.45,
    colorFlow: 0.7,
    sparkle: 0.5,
  }
}
